version: "3"
services:
  backend:
    build: ./backend
    container_name: remon_backend
    ports:
      - "8080:8080"
    networks:
      - remon-net

  ai-engine:
    build: ./ai-engine
    container_name: remon_ai
    ports:
      - "5000:5000"
    networks:
      - remon-net

  frontend:
    build: ./frontend
    container_name: remon_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE=http://localhost:8080
      - VITE_AI_BASE=http://localhost:5000
    networks:
      - remon-net

networks:
  remon-net:
    driver: bridge
