apiVersion: v1
kind: ConfigMap
metadata:
  name: remon-api-config
data:
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  OPENAI_MODEL: "gpt-4o-mini"
  LANGCHAIN_TRACING_V2: "true"
  LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
  LANGCHAIN_PROJECT: "remon_test"
  WORKERS: "2"
  QDRANT_URL: ""
  QDRANT_PREFER_GRPC: "false"
  QDRANT_TIMEOUT: "10.0"
  QDRANT_COLLECTION: "remon_regulations"
  QDRANT_USE_LOCAL: "false"
  MAPPING_TOP_K: "10"
