apiVersion: v1
kind: Service
metadata:
  name: remon-api
spec:
  selector:
    app.kubernetes.io/name: remon-api
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  type: ClusterIP

