apiVersion: v1
kind: Service
metadata:
  name: remon-postgres
spec:
  type: ExternalName
  externalName: postgres-1-postgresql.postgres.svc.cluster.local
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
