apiVersion: apps/v1
kind: Deployment
metadata:
  name: remon-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: remon-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: remon-frontend
    spec:
      imagePullSecrets:
      - name: skala25a-regcred
      containers:
      - name: remon-frontend
        image: amdp-registry.skala-ai.com/skala25a/remon-frontend   # ← 수정
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: remon-frontend-config
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20

