apiVersion: v1
kind: Service
metadata:
  name: remon-frontend
spec:
  selector:
    app.kubernetes.io/name: remon-frontend
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP

